import java.awt.event.*;
/**
 * Home form created with Net Beans
 * @author Michael McGaffick
 * @version 4/16/18
 */
public class HomeForm extends javax.swing.JFrame {
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnTable;
    private javax.swing.JButton btnInventory;
    private javax.swing.JButton btnAbout;
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel lblHeading;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHeading = new javax.swing.JLabel();
        btnReceipt = new javax.swing.JButton();
        btnTable = new javax.swing.JButton();
        btnInventory = new javax.swing.JButton();
        btnAbout = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        //Adds functions to all of the buttons
        btnAbout.addActionListener(new AboutListener());
        btnTable.addActionListener(new TableListener());
        btnReceipt.addActionListener(new ReceiptListener());
        btnInventory.addActionListener(new InventoryListener());
        btnClose.addActionListener(new CloseListener());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setBackground(new java.awt.Color(153, 255, 204));

        lblHeading.setFont(new java.awt.Font("Bookman Old Style", 0, 18)); // NOI18N
        lblHeading.setText("Restaurant Managment System");

        btnReceipt.setBackground(new java.awt.Color(0, 204, 153));
        btnReceipt.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnReceipt.setText("Receipt Managment");

        btnTable.setBackground(new java.awt.Color(0, 204, 153));
        btnTable.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnTable.setText("Table Managment");

        btnInventory.setBackground(new java.awt.Color(0, 204, 153));
        btnInventory.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnInventory.setText("Inventory Managment");

        btnAbout.setBackground(new java.awt.Color(0, 204, 153));
        btnAbout.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnAbout.setText("About");

        btnClose.setBackground(new java.awt.Color(0, 204, 153));
        btnClose.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        btnClose.setText("Save and Close");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lblHeading, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnInventory)
                            .addComponent(btnAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblHeading)
                .addGap(18, 18, 18)
                .addComponent(btnReceipt)
                .addGap(18, 18, 18)
                .addComponent(btnTable)
                .addGap(18, 18, 18)
                .addComponent(btnInventory)
                .addGap(18, 18, 18)
                .addComponent(btnAbout)
                .addGap(18, 18, 18)
                .addComponent(btnClose)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Intializes the form and prepares it upon start
     * @param args the command line arguments
     */
    public static void main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    /**
     * Listener for the about button
     * @author Michael McGaffick
     * @version 4/20/18
     */
    class AboutListener implements ActionListener
    {
        /**
         * Opens the about form and closes the home form
         * @param e the action from the button being pressed
         */
        public void actionPerformed(ActionEvent e)
        {
            Container.hf.setVisible(false);
            Container.ab.setVisible(true);
        }
    }

    /**
     * Listener for the table button
     * @author Michael McGaffick
     * @version 4/20/18
     */
    class TableListener implements ActionListener
    {
        /**
         * Opens the table management form and closes the home form
         * @param e the action from the button being pressed
         */
        public void actionPerformed(ActionEvent e)
        {
            Container.hf.setVisible(false);
            Container.tm.setVisible(true);
        }
    }

    /**
     * Listener for the receipt button
     * @author Michael McGaffick
     * @version 4/20/18
     */
    class ReceiptListener implements ActionListener
    {
        /**
         * Opens the receipt management form and closes the home form
         * @param e the action from the button being pressed
         */
        public void actionPerformed(ActionEvent e)
        {
            Container.hf.setVisible(false);
            Container.rm.setVisible(true);
        }
    }

    /**
     * Listener for the inventory button
     * @author Michael McGaffick
     * @version 4/20/18
     */
    class InventoryListener implements ActionListener
    {
        /**
         * Opens the inventory form and closes the home form
         * @param e the action from the button being pressed
         */
        public void actionPerformed(ActionEvent e)
        {
            Container.hf.setVisible(false);
            Container.im.setVisible(true);
        }
    }

    /**
     * Listener for the close button
     * @author Michael McGaffick
     * @version 4/20/18
     */
    class CloseListener implements ActionListener
    {
        /**
         * Closes the home form, thus ending the program.  Saves the inventory to a file upon exit using the File Handler class.
         * @param e the action from the button being pressed
         */
        public void actionPerformed(ActionEvent e)
        {
            try
            {
                FileHandler.saveInventory();
                Container.hf.setVisible(false);
            }
            catch(Exception ex)
            {
                System.out.println("\fSaving exception has occurred.  Your data has not been saved!" +
                    "\nPlease correct any errors regarding the inventory file and try again.");
            }
        }
    }
}
